"""Report Generator — converts structured data + templates into DOCX and PPTX with full citations."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from io import BytesIO
from pathlib import Path

import matplotlib
from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt
from pptx import Presentation
from pptx.util import Inches as PptxInches
from pptx.util import Pt as PptxPt

matplotlib.use("Agg")

from matplotlib import pyplot as plt  # noqa: E402
from matplotlib.ticker import FuncFormatter  # noqa: E402

_FOOTER_TEXT = "Generated by Fabric Sales Agent Accelerator"
_TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"
_DEFAULT_DOCX_TEMPLATE = "account_plan.md"


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------


@dataclass
class ForecastItem:
    """Single product category forecast."""

    category: str
    current_fy_revenue: float
    growth_rate: float
    projected_fy_revenue: float


@dataclass
class ForecastData:
    """FY quota forecast data."""

    customer_name: str
    current_fy_total: float
    projected_fy_total: float
    overall_growth_rate: float
    methodology: str
    items: list[ForecastItem] = field(default_factory=list)


@dataclass
class ReportData:
    """Structured payload consumed by the report generators."""

    title: str
    customer_name: str
    generated_at: datetime
    pipeline_data: list[dict] = field(default_factory=list)
    research_data: dict = field(default_factory=dict)
    sharepoint_docs: list[dict] = field(default_factory=list)
    additional_context: str | None = None
    forecast_data: ForecastData | None = None


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _fmt_timestamp(dt: datetime) -> str:
    return dt.strftime("%Y-%m-%d %H:%M")


def _build_citations(data: ReportData) -> list[str]:
    """Collect every citable source from *data* into a flat list of strings."""
    citations: list[str] = []

    citations.append(f"Fabric pipeline query — {_fmt_timestamp(data.generated_at)}")

    for article in data.research_data.get("articles", []):
        url = article.get("url", "")
        source = article.get("source", "Unknown")
        title = article.get("title", "Untitled")
        entry = f"{title} — {source}"
        if url:
            entry += f" ({url})"
        citations.append(entry)

    for doc in data.sharepoint_docs:
        name = doc.get("name", "Untitled")
        url = doc.get("url", "")
        entry = f"SharePoint: {name}"
        if url:
            entry += f" ({url})"
        citations.append(entry)

    return citations


def _load_template(template_name: str) -> str:
    """Return the raw text of a markdown template, or empty string if missing."""
    path = _TEMPLATES_DIR / template_name
    if path.exists():
        return path.read_text(encoding="utf-8")
    return ""


def _generate_forecast_chart(forecast: ForecastData) -> BytesIO:
    """Generate a bar chart comparing current vs projected FY revenue by category."""
    categories = [item.category for item in forecast.items]
    current = [item.current_fy_revenue / 1000 for item in forecast.items]
    projected = [item.projected_fy_revenue / 1000 for item in forecast.items]

    fig, ax = plt.subplots(figsize=(8, 4))
    x = range(len(categories))
    width = 0.35

    ax.bar([index - width / 2 for index in x], current, width, label="Current FY", color="#0078D4")
    ax.bar([index + width / 2 for index in x], projected, width, label="Projected FY", color="#50E6FF")

    ax.set_ylabel("Revenue ($K)")
    ax.set_title(f"FY Quota Forecast — {forecast.customer_name}")
    ax.set_xticks(list(x))
    ax.set_xticklabels(categories, rotation=30, ha="right", fontsize=9)
    ax.legend()
    ax.yaxis.set_major_formatter(FuncFormatter(lambda value, _: f"${value:,.0f}K"))

    fig.tight_layout()

    buffer = BytesIO()
    fig.savefig(buffer, format="png", dpi=150, bbox_inches="tight")
    plt.close(fig)
    buffer.seek(0)
    return buffer


# ---------------------------------------------------------------------------
# DOCX generation
# ---------------------------------------------------------------------------


def generate_docx(
    data: ReportData,
    template_name: str | Path,
    output_path: str | Path | None = None,
) -> str:
    """Create a Word document from *data* and return the resolved output path.

    Parameters
    ----------
    data:
        The structured report payload.
    template_name:
        Name of the markdown template, or the output path when ``output_path`` is omitted.
    output_path:
        Destination file path for the ``.docx`` file.
    """
    if output_path is None:
        output_path = template_name
        template_name = _DEFAULT_DOCX_TEMPLATE

    _ = _load_template(str(template_name))  # reserved for future template-driven rendering

    doc = Document()
    style = doc.styles["Normal"]
    style.font.size = Pt(11)
    style.font.name = "Calibri"

    # -- Title page ----------------------------------------------------------
    title_para = doc.add_heading(data.title, level=0)
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run(f"Prepared for {data.customer_name}")
    run.font.size = Pt(14)

    date_para = doc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    date_para.add_run(_fmt_timestamp(data.generated_at)).font.size = Pt(12)

    doc.add_page_break()

    # -- Pipeline Overview ---------------------------------------------------
    doc.add_heading("Pipeline Overview", level=1)

    if data.pipeline_data:
        columns = ["Deal", "Value", "Stage", "Close Date"]
        table = doc.add_table(rows=1, cols=len(columns))
        table.style = "Light Shading Accent 1"
        table.alignment = WD_TABLE_ALIGNMENT.CENTER

        for idx, col_name in enumerate(columns):
            table.rows[0].cells[idx].text = col_name

        for deal in data.pipeline_data:
            row = table.add_row()
            row.cells[0].text = str(deal.get("deal_name", ""))
            row.cells[1].text = f"${deal.get('value', 0):,.0f}"
            row.cells[2].text = str(deal.get("stage", ""))
            row.cells[3].text = str(deal.get("close_date", ""))
    else:
        doc.add_paragraph("No pipeline data available.")

    # -- Customer Intelligence -----------------------------------------------
    doc.add_heading("Customer Intelligence", level=1)

    summary = data.research_data.get("summary", "")
    company = data.research_data.get("company_name", data.customer_name)
    if summary:
        doc.add_paragraph(summary)
    elif company:
        doc.add_paragraph(f"Intelligence gathered for {company}.")

    articles = data.research_data.get("articles", [])
    if articles:
        doc.add_heading("Recent News", level=2)
        for article in articles:
            title = article.get("title", "Untitled")
            source = article.get("source", "")
            date = article.get("date", "")
            article_summary = article.get("summary", "")
            url = article.get("url", "")
            bullet_text = f"{title}"
            if source:
                bullet_text += f" — {source}"
            if date:
                bullet_text += f" ({date})"
            if url:
                bullet_text += f"\n{url}"
            if article_summary:
                bullet_text += f"\n{article_summary}"
            doc.add_paragraph(bullet_text, style="List Bullet")

    # -- Internal Context ----------------------------------------------------
    doc.add_heading("Internal Context", level=1)

    if data.sharepoint_docs:
        for sp_doc in data.sharepoint_docs:
            name = sp_doc.get("name", "Untitled")
            url = sp_doc.get("url", "")
            excerpt = sp_doc.get("excerpt", "")
            heading_text = name
            if url:
                heading_text += f" — {url}"
            doc.add_heading(heading_text, level=2)
            if excerpt:
                doc.add_paragraph(excerpt)
    else:
        doc.add_paragraph("No SharePoint documents referenced.")

    if data.additional_context:
        doc.add_heading("Additional Context", level=2)
        doc.add_paragraph(data.additional_context)

    # -- FY Quota Forecast ---------------------------------------------------
    if data.forecast_data:
        forecast = data.forecast_data
        doc.add_heading("FY Quota Forecast", level=1)

        growth_pct = f"{forecast.overall_growth_rate * 100:.1f}%"
        doc.add_paragraph(
            f"Projected revenue for {forecast.customer_name}: "
            f"${forecast.projected_fy_total:,.0f} "
            f"({growth_pct} growth from ${forecast.current_fy_total:,.0f} current FY)."
        )

        chart_buffer = _generate_forecast_chart(forecast)
        doc.add_picture(chart_buffer, width=Inches(6))
        doc.paragraphs[-1].alignment = WD_ALIGN_PARAGRAPH.CENTER

        table = doc.add_table(rows=1, cols=4, style="Light Grid Accent 1")
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        headers = ["Product Category", "Current FY", "Growth %", "Projected FY"]
        for index, header in enumerate(headers):
            table.rows[0].cells[index].text = header

        for item in forecast.items:
            row = table.add_row()
            row.cells[0].text = item.category
            row.cells[1].text = f"${item.current_fy_revenue:,.0f}"
            row.cells[2].text = f"{item.growth_rate * 100:.1f}%"
            row.cells[3].text = f"${item.projected_fy_revenue:,.0f}"

        total_row = table.add_row()
        total_row.cells[0].text = "Total"
        total_row.cells[1].text = f"${forecast.current_fy_total:,.0f}"
        total_row.cells[2].text = growth_pct
        total_row.cells[3].text = f"${forecast.projected_fy_total:,.0f}"
        for cell in total_row.cells:
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.bold = True

        doc.add_paragraph(f"Methodology: {forecast.methodology}", style="Intense Quote")

    # -- Sources & Citations -------------------------------------------------
    doc.add_page_break()
    doc.add_heading("Sources & Citations", level=1)

    for citation in _build_citations(data):
        doc.add_paragraph(citation, style="List Number")

    # -- Footer --------------------------------------------------------------
    footer_text = f"{_FOOTER_TEXT} — {_fmt_timestamp(data.generated_at)}"
    for section in doc.sections:
        footer = section.footer
        footer.is_linked_to_previous = False
        footer_para = footer.paragraphs[0] if footer.paragraphs else footer.add_paragraph()
        footer_para.text = footer_text
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in footer_para.runs:
            run.font.size = Pt(8)

    resolved = str(Path(output_path).resolve())
    doc.save(resolved)
    return resolved


# ---------------------------------------------------------------------------
# PPTX generation
# ---------------------------------------------------------------------------


def generate_pptx(data: ReportData, template_name: str, output_path: str) -> str:
    """Create a PowerPoint deck from *data* and return the resolved output path.

    Parameters
    ----------
    data:
        The structured report payload.
    template_name:
        Name of the markdown template (reserved for future use).
    output_path:
        Destination file path for the ``.pptx`` file.
    """
    _ = _load_template(template_name)

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    footer_stamp = f"{_FOOTER_TEXT} — {_fmt_timestamp(data.generated_at)}"

    def _add_footer(slide: object) -> None:  # type: ignore[override]
        """Add a small footer text box to the bottom of *slide*."""
        from pptx.util import Emu as _Emu

        txbox = slide.shapes.add_textbox(  # type: ignore[attr-defined]
            _Emu(0),
            prs.slide_height - PptxInches(0.4),
            prs.slide_width,
            PptxInches(0.4),
        )
        tf = txbox.text_frame
        tf.text = footer_stamp
        for para in tf.paragraphs:
            para.font.size = PptxPt(8)
            para.alignment = WD_ALIGN_PARAGRAPH.CENTER

    # -- Slide 1: Title ------------------------------------------------------
    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = data.title
    slide.placeholders[1].text = f"Prepared for {data.customer_name}\n{_fmt_timestamp(data.generated_at)}"
    _add_footer(slide)

    # -- Slide 2: Pipeline ---------------------------------------------------
    blank_layout = prs.slide_layouts[5]  # blank
    slide = prs.slides.add_slide(blank_layout)
    # heading
    txbox = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(0.3), PptxInches(12), PptxInches(0.6))
    txbox.text_frame.text = "Pipeline Overview"
    txbox.text_frame.paragraphs[0].font.size = PptxPt(28)
    txbox.text_frame.paragraphs[0].font.bold = True

    if data.pipeline_data:
        rows = len(data.pipeline_data) + 1
        cols = 4
        table_shape = slide.shapes.add_table(
            rows, cols, PptxInches(0.5), PptxInches(1.2), PptxInches(12), PptxInches(4)
        )
        table = table_shape.table
        headers = ["Deal", "Value", "Stage", "Close Date"]
        for ci, h in enumerate(headers):
            table.cell(0, ci).text = h
        for ri, deal in enumerate(data.pipeline_data, start=1):
            table.cell(ri, 0).text = str(deal.get("deal_name", ""))
            table.cell(ri, 1).text = f"${deal.get('value', 0):,.0f}"
            table.cell(ri, 2).text = str(deal.get("stage", ""))
            table.cell(ri, 3).text = str(deal.get("close_date", ""))
    else:
        txbox2 = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(1.5), PptxInches(12), PptxInches(1))
        txbox2.text_frame.text = "No pipeline data available."

    _add_footer(slide)

    # -- Slide 3: Intelligence -----------------------------------------------
    slide = prs.slides.add_slide(blank_layout)
    txbox = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(0.3), PptxInches(12), PptxInches(0.6))
    txbox.text_frame.text = "Customer Intelligence"
    txbox.text_frame.paragraphs[0].font.size = PptxPt(28)
    txbox.text_frame.paragraphs[0].font.bold = True

    body_box = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(1.2), PptxInches(12), PptxInches(5.5))
    tf = body_box.text_frame
    tf.word_wrap = True

    summary = data.research_data.get("summary", "")
    company = data.research_data.get("company_name", data.customer_name)
    if summary:
        tf.text = summary
    elif company:
        tf.text = f"Intelligence gathered for {company}."

    for article in data.research_data.get("articles", []):
        p = tf.add_paragraph()
        title = article.get("title", "Untitled")
        source = article.get("source", "")
        bullet = f"• {title}"
        if source:
            bullet += f" — {source}"
        p.text = bullet
        p.font.size = PptxPt(14)

    _add_footer(slide)

    # -- Slide 4: Sources & Citations ----------------------------------------
    slide = prs.slides.add_slide(blank_layout)
    txbox = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(0.3), PptxInches(12), PptxInches(0.6))
    txbox.text_frame.text = "Sources & Citations"
    txbox.text_frame.paragraphs[0].font.size = PptxPt(28)
    txbox.text_frame.paragraphs[0].font.bold = True

    cite_box = slide.shapes.add_textbox(PptxInches(0.5), PptxInches(1.2), PptxInches(12), PptxInches(5.5))
    cite_tf = cite_box.text_frame
    cite_tf.word_wrap = True

    citations = _build_citations(data)
    if citations:
        cite_tf.text = citations[0]
        for c in citations[1:]:
            p = cite_tf.add_paragraph()
            p.text = c
            p.font.size = PptxPt(12)
    else:
        cite_tf.text = "No sources to cite."

    _add_footer(slide)

    resolved = str(Path(output_path).resolve())
    prs.save(resolved)
    return resolved
